framework:
  github: pedestal/pedestal
  version: 0.6

  image: clojure:openjdk-11-lein-slim-buster

  build:
    - lein uberjar

  binaries:
    - target/the-benchmarker-pedestal-0.0.1-SNAPSHOT-standalone.jar

  command: java -Xms2G -server -Xmx2G -XX:+UseStringDeduplication -XX:+UseParallelGC -Dvertx.disableMetrics=true -Dvertx.threadChecks=false -Dvertx.disableContextTimings=true -Dvertx.disableTCCL=true -Dvertx.disableH2c=true -Dvertx.disableWebsockets=true -Dvertx.disableHttpHeadersValidation=true -Dvertx.flashPolicyHandler=false -Djava.net.preferIPv4Stack=true -jar target/the-benchmarker-pedestal-0.0.1-SNAPSHOT-standalone.jar
